module.exports = {
    dsa: [
        //"LinearSearchList",
        //"BinarySearchList",
        //"TwoCrystalBalls",
        //"BubbleSort",
        //"DoublyLinkedList",
        //"Queue",
        //"Stack",
        //"ArrayList",
        //"MazeSolver",
        //"QuickSort",
        "BTPreOrder",
        "BTInOrder",
        "BTPostOrder",
        "BTBFS",
        "CompareBinaryTrees",
        "BFSOnBST",
        "DFSOnBST",
        "LRU",
        "DFSGraphList",
        "Trie",
        "BFSGraphMatrix",
        "Map",
        "MinHeap",
    ],
}

